# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-12 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHTModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('humid', models.FloatField()),
                ('temp', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='HumidModel',
        ),
        migrations.DeleteModel(
            name='TempModel',
        ),
    ]
